Details popup
asdt560/Portfolio pull request #11
Opened 2022-09-06 23:29 UTC by asdt560

Made the main page's projects section dynamic, pulling project information from a javascript array. Made similarly dynamic modals.

2022-09-06 23:38 UTC, MahmoudBakr23 requested changes
Hello @asdt560 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Well done with following the Figma design
- Great work with javascript
- Descriptive PR and Readme file
- Correct Linters

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process improves the code you wrote, not criticizes it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to mention me @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-06 23:38 UTC, MahmoudBakr23 commented on styles.css
> +}
- [ ] Well done styling the popup window so far. However, you may have to write some more CSS code to shape the widths and heights of it across multiple screen sizes. Please take a look at the two images down below.
**Desktop**
![Screenshot (2)](https://user-images.githubusercontent.com/47625407/188758083-628aaa84-67de-42b8-ac8f-e76ab829622c.png)
**Mobile**
![Screenshot (1)](https://user-images.githubusercontent.com/47625407/188758088-38087247-c2e3-422c-aa7f-213499d1b745.png)

- [ ] Kindly adjust your design to make it fit the multiple sizes of a screen 🙏

2022-09-07 01:13 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @asdt560 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 01:13 UTC, tresorsawasawa commented on script.js
> +
- [ ] Good job doing some of the changes required by the previous reviewer. But as he mentioned,  kindly make sure your popup design matches the one from your chosen Figma template. Right now the **ClosePopup*, **See Live**, and **See Source** buttons disappear on some desktop screen sizes like on the image below:

### Your Design
![Screenshot from 2022-09-07 02-59-23](https://user-images.githubusercontent.com/83042742/188765678-e6b446d8-1191-41c1-bfd7-cf76b82e659a.png) 
![Screenshot from 2022-09-07 03-07-29](https://user-images.githubusercontent.com/83042742/188766612-95730b19-db5e-433f-8d38-b1c2c481d0ed.png) |

#### Figma Design
![Screenshot from 2022-09-07 03-00-36](https://user-images.githubusercontent.com/83042742/188765888-0ae1bf91-3f89-45d9-8bfd-6d9a17baabfa.png)

2022-09-07 12:11 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 

## Hi @asdt560 👋, 

Well done for implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code.

- n/a

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 15:07 UTC, merged